# Pandas Exercises for Data Analysis

*by Selva Prabhakaran*
From the website: https://www.machinelearningplus.com/python/101-pandas-exercises-python/

[Pandas Cheet Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

#### 1. (L1) pandas를 `pd`로 임포트 및 버전 확인

In [1]:
import pandas as pd

pd.__version__

'1.5.3'

#### 2. (L1) 1차원 배열을 pandas series 형태로 출력한다.

In [3]:
import numpy as np

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

ser.to_frame().reset_index().iloc[:5]

index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4

#### 3. (L1) 두 개의 pandas series를 연결하여 DataFrame의 형태로 나타낸다.

In [7]:
# Inputs
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

pd.concat([ser1, ser2], axis=1).iloc[:5]

0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4

#### 4. (L2) 두 개의 pandas series에서 겹치는 값을 제외하고 연결한다.

In [8]:
# Input
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

union = np.union1d(ser1, ser2)
intersection = np.intersect1d(ser1, ser2)

print(union, intersection)
union[~pd.Series(union).isin(intersection)]

[1 2 3 4 5 6 7 8] [4 5]


array([1, 2, 3, 6, 7, 8])

#### 5. (L2) pandas series에서 0.25, 0.75 퍼센트에 위치하는 값을 추출한다.

In [10]:
# Input

ser = pd.Series(np.random.normal(10, 5, 25))

for method in [pd.Series.max, pd.Series.min, pd.Series.median]:
    print(method(ser))
print(ser.quantile(0.25))
print(ser.quantile(0.75))


20.36828091280382
-4.235579323691169
8.963556180411693
6.205431077649264
13.464796401591313


#### 6. (L2) pandas series에서 수치를 기준으로 10개의 분기를 나누고 각각에 label을 부여한다.

In [9]:
# Input

ser = pd.Series(np.random.random(20))

with_cut = pd.cut(
    ser,
    bins=np.percentile(ser, np.arange(0, 110, 10)),
    labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'],
    include_lowest=True
)

with_qcut = pd.qcut(
    ser,
    q=np.arange(0, 1.1, .1),
    labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']
)

np.all(with_cut == with_qcut)

True

#### 7. (L1) pandas series를 7x5 형태의 dataframe으로 변환한다.

In [14]:
# Input

ser = pd.Series(np.random.randint(1, 10, 35))

pd.DataFrame(
    ser.to_numpy().reshape((7,5))
)

0  1  2  3  4
0  7  3  9  2  3
1  6  6  9  4  9
2  6  8  5  5  4
3  1  8  3  9  3
4  2  5  9  4  1
5  4  1  1  1  4
6  9  3  9  7  9

#### 8. (L1) 두 개의 pandas series를 수직, 수평으로 이어붙인다.

In [17]:
# Input

ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

horizontally = pd.concat([ser1, ser2], axis=0)
vertically = pd.concat([ser1, ser2], axis=1)
print(horizontally, vertically)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object    0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


#### 9. (L2) 실제값과 예측값 사이의 차이값을 구한다. (MSE)

**NOTE**: This question means that we need to calculate the mean squared error between the two series, using the formula:

$$MSE = \dfrac{1}{n} * \sum \left(truth - pred\right)^2$$

In [12]:
# Input
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

np.mean(
    (truth-pred)**2  # Squares of errors
)

0.2548388417322032

#### 10. (L2) 각 값들을 Uppercase로 만든다.

In [20]:
# Input

ser = pd.Series(['how', 'to', 'kick', 'ass?'])

ser.apply(str.title)

0     How
1      To
2    Kick
3    Ass?
dtype: object

#### 11. (L2) pandas series 앞의 값을 뺀 차이 값을 획득한다.

In [14]:
# Input

ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

print(ser.tolist())
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[1, 3, 6, 10, 15, 21, 27, 35]
[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


#### 12. (L2) pandas series를 date-strings로 변환한다.

Desired output:

```
0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]
```

In [15]:
# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

ser.astype('datetime64[ns]')

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

#### 13. (L2) pandas series로 부터 다음의 값을 추출한다.

Desired output:

```
Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']
```

In [17]:
# Input

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Manual

dates = []
week_numbers = []
day_numbers = []
weekdays = []
weekday_names = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Friday']

for index, date in enumerate(ser.astype('datetime64[ns]')):
    dates.append(index)
    week_numbers.append(date.week)
    day_numbers.append(date.day_of_year)
    weekdays.append(weekday_names[date.weekday()])

print(dates)
print(week_numbers)
print(day_numbers)
print(weekdays)

[0, 1, 2, 3, 4, 5]
[53, 5, 9, 14, 19, 23]
[1, 33, 63, 94, 125, 157]
['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


#### 14. (L2) `fruit` 정보에서 각 과일별로 `weights`의 평균을 계산한다.

In [18]:
# Inputs

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

fruits_dataframe = pd.DataFrame(
    np.vstack([fruit, weights])
).T
fruits_dataframe.columns = ["fruit", "weight"]
fruits_dataframe.groupby('fruit').mean()

weight
fruit         
apple     4.75
banana    5.40
carrot    9.00

#### 15. (L3) missing 값을 가장 빈번히 등장하는 값으로 치환한다.

In [19]:
# Input

my_str = 'dbc deb abed gade'

uniques, counts = np.unique(
    pd.Series([*my_str]),
    return_counts=True
)
least_frequent_character = uniques[np.argmin(counts)]

my_str.replace(' ', least_frequent_character)

'dbccdebcabedcgade'

#### 16. (L3) `2000-01-01`에서 시작하여 10개의 week을 나타내고, 각 주별로 랜덤된 숫자를 가지는 DataFrame을 생성한다.

In [20]:
pd.DataFrame({
    'date': pd.date_range('2020-01-01', periods=10, freq='7D'),
    'number': np.random.randint(low=0, high=100, size=10)
})

date  number
0 2020-01-01      96
1 2020-01-08      97
2 2020-01-15      46
3 2020-01-22      36
4 2020-01-29      65
5 2020-02-05      64
6 2020-02-12       4
7 2020-02-19      18
8 2020-02-26      50
9 2020-03-04      98

#### 17. (L2) `boston` 데이터 셋에서 데이터의 일부를 추출한다.
- 50개씩 chunking 한 후에 각 chunk 마다 1번째 행을 가져와서 새로운 데이터로 생성한다.

In [38]:
import requests

BOSTON_URL = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"

pd.DataFrame([
    chunk.iloc[0,:]  # This takes first line
    for chunk in pd.read_csv(
        BOSTON_URL,
        chunksize=50  # Of every chunk that is 50 rows long
    )
]).reset_index().drop('index', axis=1)

crim    zn  indus  chas    nox     rm    age     dis   rad    tax  \
0    0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900   1.0  296.0   
1    0.08873  21.0   5.64   0.0  0.439  5.963   45.7  6.8147   4.0  243.0   
2    0.14866   0.0   8.56   0.0  0.520  6.727   79.9  2.7778   5.0  384.0   
3    1.65660   0.0  19.58   0.0  0.871  6.122   97.3  1.6180   5.0  403.0   
4    0.01778  95.0   1.47   0.0  0.403  7.135   13.9  7.6534   3.0  402.0   
5    0.14030  22.0   5.86   0.0  0.431  6.487   13.0  7.3967   7.0  330.0   
6    0.04417  70.0   2.24   0.0  0.400  6.871   47.4  7.8278   5.0  358.0   
7    0.06211  40.0   1.25   0.0  0.429  6.490   44.4  8.7921   1.0  335.0   
8   25.04610   0.0  18.10   0.0  0.693  5.987  100.0  1.5888  24.0  666.0   
9    6.71772   0.0  18.10   0.0  0.713  6.749   92.6  2.3236  24.0  666.0   
10   0.22438   0.0   9.69   0.0  0.585  6.027   79.7  2.4982   6.0  391.0   

    ptratio       b  lstat  medv  
0      15.3  396.90   4.98  24.0  
1      16.8  395.56  13.45  19.7  
2      20.9  394.76   9.42  27.5  
3      14.7  372.80  14.10  21.5  
4      17.0  384.30   4.45  32.9  
5      19.1  396.28   5.90  24.4  
6      14.8  390.86   6.07  24.8  
7      19.7  396.90   5.98  22.9  
8      20.2  396.90  26.77   5.6  
9      20.2    0.32  17.44  13.4  
10     19.2  396.90  14.33  16.8

#### 18. (L2) 보스턴 집값 데이터를 불러온다. 집값의 중앙값 (`medv`)을 기준으로 25보다 작으면 'Low'를 25보다 크다면 'High'로 치환하여 데이터를 불러온다.

In [39]:
def categorize(row: np.generic):
    row['medv'] = 'Low' if row['medv'] < 25 else 'High'
    return row

# 확인용
via_apply = pd.read_csv(BOSTON_URL).apply(categorize, axis=1) 

# TODO
via_converters = pd.read_csv(BOSTON_URL, converters={
    'medv': lambda median_value: 'Low' if float(median_value) < 25 else 'High'
})
np.all(via_apply == via_converters)

True

#### 19. (L2) 보스턴 집값 데이터를 불러온 후에 데이터의 정보를 확인한다.

In [40]:
# Input
boston = pd.read_csv(BOSTON_URL)

print(
    boston.info(),
    '\n',
    boston.describe(),
    '\n',
    boston.to_numpy(),
    '\n',
    boston.to_numpy().tolist()
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB
None 
              crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695 

#### 20. (L1) 자동차 데이터에서 가장 갑이 비싼 자동차의 'Manufacturer', 'Model', 'Type'을 반환한다.

In [47]:
# Input
CARS93_URL = "https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv"
cars = pd.read_csv(CARS93_URL)

cars.loc[cars['Price'].argmax(), ['Manufacturer', 'Model', 'Type']]

Manufacturer    Mercedes-Benz
Model                    300E
Type                  Midsize
Name: 58, dtype: object

#### 21. (L2) 자동차 데이터의 열 이름 중 `Type`을 `CarType`으로 바꾸고, `.`이 들어있다면 `_`로 대채한다.

Desired output:

```python
 print(df.columns)
#> Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
#>        'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
#>        'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')
```

In [48]:
# Input
cars = pd.read_csv(CARS93_URL)

cars.columns = [
    column.replace('.', '_')
    for column in cars.columns
]
cars.rename(columns={'Type': 'CarType'})

Manufacturer    Model  CarType  Min_Price  Price  Max_Price  MPG_city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG_highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn_circle Rear_seat_room  Luggage_room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

#### 22. (L2) 자동차 데이터에서 각 열별로 nan 값을 확인한다.

In [51]:
# Input
cars = pd.read_csv(CARS93_URL)

nans = cars.isna().astype(int).sum(axis=0)
nans[
    nans == nans.max()
]

Luggage.room    19
dtype: int64

#### 23. (L2) nan 값이 `Min.Price` 혹은 `Max.Price`에 존재하면 평균 값으로 대채한다.

In [52]:
# Input
cars = pd.read_csv(CARS93_URL)

for column in ['Min.Price', 'Max.Price']:
    cars[column].fillna(
        cars[column].mean().round(1),
        inplace=True
    )
cars

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize       17.1   37.7       44.6      19.0   
4           BMW     535i  Midsize       17.1   30.0       21.5      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

#### 24. (L1) 데이터에 `Manufacturer`, `Model` and `Type`만 출력한다.

In [53]:
# Input
dataframe = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

dataframe[['Manufacturer', 'Model', 'Type']].iloc[::20]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

#### 25. (L2) nan값을 'missing'이라는 값으로 변경하고, 'Manufacturer', 'Model' and 'Type'를 연결하여 Primary Key값으로 만든다.

Desired output:

```python
                       Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small           Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize      missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                Audi       90  Compact       25.9       32.3
Audi_100_Midsize               Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                BMW     535i  Midsize        NaN        NaN
```

In [54]:
# Input
dataframe = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

dataframe[['Manufacturer', 'Model', 'Type']] = dataframe[['Manufacturer', 'Model', 'Type']].fillna(value='missing')
dataframe.set_index(
    dataframe['Manufacturer'] + '_' + dataframe['Model'] + '_' + dataframe['Type']
)

Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small              Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize         missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                   Audi       90  Compact       25.9       32.3
Audi_100_Midsize                  Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                   BMW     535i  Midsize        NaN        NaN
...                                ...      ...      ...        ...        ...
Volkswagen_Eurovan_Van      Volkswagen  Eurovan      Van       16.6       22.7
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact       17.6       22.4
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty       22.9       23.7
Volvo_240_Compact                Volvo      240  Compact       21.8       23.5
missing_850_Midsize            missing      850  Midsize       24.8       28.5

[93 rows x 5 columns]

#### 26. (L2) 'a' 열에서 5번째로 큰 값을 가지는 행을 반환한다.

In [55]:
# Input
dataframe = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

np.argsort(  # Sort
    dataframe['a']
)[::-1][5]  # Reverse and take the 5th element

4

#### 27. (L2) pandas series에서 5%이하 값은 5%값으로, 95%이상 값은 95%값으로 대치한다. (이상값 처리)

In [57]:
# Input

ser = pd.Series(np.logspace(-2, 2, 30))

ser[
    ser < ser.quantile(0.05)
] = ser.quantile(0.05)
ser[
    ser > ser.quantile(0.95)
] = ser.quantile(0.95)

ser[:5]

0    0.016049
1    0.016049
2    0.018874
3    0.025929
4    0.035622
dtype: float64

#### 28. (L3) 각 행이 4차원을 가지고 있다고 할 때, 각 행별로 가장 가까운 행의 이름을 발견하고 거리를 구한다.

Desired output:

```python
   p   q   r   s nearest_row   dist
a  57  77  13  62           i  116.0
b  68   5  92  24           a  114.0
c  74  40  18  37           i   91.0
d  80  17  39  60           i   89.0
e  93  48  85  33           i   92.0
f  69  55   8  11           g  100.0
g  39  23  88  53           f  100.0
h  63  28  25  61           i   88.0
i  18   4  73   7           a  116.0
j  79  12  45  34           a   81.0
```

In [58]:
# Input

df = pd.DataFrame(np.random.randint(1,100,40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

euclidean_distances = {
    'nearest_row': [],
    'dist': []
}

for first_row in range(0, df.shape[0]):
    distances = []
    ids = []
    for second_row in range(0, df.shape[0]):
        if first_row == second_row:
            continue
        euclidean_distance = np.linalg.norm(
            (df.iloc[second_row] - df.iloc[first_row])
        )
        distances.append(euclidean_distance)
        ids.append(df.iloc[second_row].name)
    series = pd.Series(distances, index=ids)
    euclidean_distances['nearest_row'].append(
        series.index[series.argmin()]
    )
    euclidean_distances['dist'].append(
        series.min()
    )
distances_df = pd.DataFrame(euclidean_distances, index=df.index)
pd.concat([df, distances_df], axis=1)

p   q   r   s nearest_row       dist
a  26   7  40   3           h  48.197510
b  69  15  74  92           c  65.962110
c  44  16  24  57           i  58.974571
d  18  87  79  70           e  51.816986
e  66  82  63  60           i  45.672749
f  80  74   5  67           e  60.605280
g  85  52  76  17           i  35.171011
h  38  34  75  18           i  39.012818
i  61  54  52  26           g  35.171011
j  58  91  33   3           i  47.623524

#### 29. (L2) 생성한 데이터에서 최소/최대값을 계산한다.

In [59]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

df.apply(lambda row: row.min()/row.max(), axis=1)

0    0.181818
1    0.151515
2    0.040816
3    0.103448
4    0.022727
5    0.191919
6    0.076087
7    0.142857
dtype: float64

#### 30. (L2) 각 열별 값을 기준으로 정규화한 데이터를 가진다. 최대 최소는 각각 0, 1을 가지도록 만든다.

In [66]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

df.apply(lambda col: (col - col.mean()) / col.std()).apply(lambda col: col - col.min()).apply(lambda col: (col / col.max()).round(2))

0     1     2     3     4     5     6     7     8     9
0  0.04  0.00  1.00  0.27  0.24  0.20  0.13  0.00  0.44  0.00
1  0.74  1.00  0.32  0.80  1.00  0.86  1.00  0.20  0.38  0.99
2  0.57  0.40  0.10  0.88  0.49  1.00  0.68  0.24  0.79  0.93
3  0.00  0.31  0.50  0.79  0.00  0.24  0.34  0.37  0.00  0.17
4  0.68  0.07  0.00  0.00  0.46  0.73  0.65  0.17  0.07  0.86
5  0.06  0.26  0.29  0.98  0.93  0.48  0.00  0.72  1.00  0.38
6  0.68  0.60  0.49  1.00  0.61  0.27  0.80  1.00  0.63  1.00
7  1.00  1.00  0.57  0.87  0.92  0.00  0.35  0.56  0.23  0.20

#### 31. (L2) 대각행렬의 값을 0으로 치환한다.

In [4]:
# Input

df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

eye = pd.DataFrame(np.eye(*df.shape))

df[
    eye != 1.0
][
    pd.DataFrame(np.rot90(eye)) != 1.0
].fillna(value=0)

0     1     2     3     4     5     6     7     8     9
0   0.0  63.0  69.0  33.0  40.0  42.0  27.0  45.0  65.0   0.0
1   4.0   0.0  83.0  86.0  69.0  73.0  22.0   1.0   0.0  11.0
2  39.0  28.0   0.0  19.0  53.0  44.0  23.0   0.0  87.0  26.0
3  88.0  82.0  71.0   0.0  24.0  11.0   0.0  15.0  86.0  89.0
4  95.0  56.0  84.0  80.0   0.0   0.0  62.0  45.0   8.0  86.0
5   7.0  47.0  63.0  37.0   0.0   0.0  81.0  21.0  80.0  68.0
6  31.0  60.0  12.0   0.0  60.0  93.0   0.0  11.0  82.0  31.0
7  32.0  17.0   0.0  65.0  52.0  46.0  32.0   0.0  72.0  72.0
8   9.0   0.0  49.0  10.0  38.0  11.0  22.0  19.0   0.0  92.0
9   0.0   4.0  54.0  41.0  92.0  80.0  48.0   5.0  78.0   0.0

#### 32. (L2) 데이터를 첫번째 컬럼(과일명) 기준으로 group화 한다.

In [5]:
# Input
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])
df_grouped.get_group('apple')

col1      col2  col3
0  apple  0.095371     0
3  apple  0.283008    14
6  apple  0.487024     6

#### 33. (L2) 바나나에 대하여 2번째로 비싼 가격을 출력한다.

In [6]:
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

df.groupby(['fruit']).get_group('banana')['price'].sort_values(ascending=False).values[1]

10

#### 34. (L2) 두 개의 DataFrame을 결합한다.

In [83]:
# Inputs

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

df1.merge(df2, left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], how='inner', suffixes=['_df1', '_df2'])

fruit weight  price_df1  pazham  kilo  price_df2
0   apple   high         13   apple  high          2
1  orange    low         12  orange   low         13
2   apple   high         13   apple  high          2
3  orange    low         10  orange   low         13
4   apple   high          0   apple  high          2
5  orange    low          1  orange   low         13

#### 35. (L2) 하나로 연결되어 있는 데이터를 3개의 열로 분할한다

Desired output:

```python
0 STD        City        State
1  33     Kolkata  West Bengal
2  44     Chennai   Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
```

In [7]:
# Input
df = pd.DataFrame(["STD, City State",
"33, Kolkata Bengal",
"44, Chennai Nadu",
"40, Hyderabad Telengana",
"80, Bangalore Karnataka"], columns=['row'])

split = df.row.str.replace(',', ' ').str.split(' ', expand=True)
split.columns = split.iloc[0]
split = split[1:]
split

0 STD         City      State
1  33      Kolkata     Bengal
2  44      Chennai       Nadu
3  40    Hyderabad  Telengana
4  80    Bangalore  Karnataka